### ISSUE TITLE
Add a resource to a data package resources array

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#14]
The user can add a resource by going to the `datapackage.metadata` dict and adding it himself. However, if she does so, the new resource wouldn't appear in the `datapackage.resources` tuple, so the datapackage would be in an inconsistent state (the metadata says one thing, the `datapackage` says another).

I see two options of solving this:

1. Add a `.add_resouce()` method, which adds the resource to the metadata and updates the resources list;
2. Check the metadata every time the user asks for `datapackage.resources`, loading/removing resources as needed.

The code for the first option would look like:

```python
import datapackage

dp = datapackage.DataPackage('http://data.okfn.org/data/core/gdp/datapackage.json')
new_resource = {
    'name': 'foo',
    'url': 'http://data.okfn.org/data/core/gdp/data/foo.csv'
}
try:
    dp.add_resource(new_resource)
except datapackage.exceptions.ResourceError as e:
    pass  # There was an error. Tell the user.

dp.resources[-1]  # This should contain the new resource, with the data already loaded.
```

The second option would look like:
```python
import datapackage

dp = datapackage.DataPackage('http://data.okfn.org/data/core/gdp/datapackage.json')
new_resource = {
    'name': 'foo',
    'url': 'http://data.okfn.org/data/core/gdp/data/foo.csv'
}
dp.metadata.get('resources', []).append(new_resource)

# ... many lines of code goes by ...

try:
    resource = dp.resources[-1]
except datapackage.exceptions.ResourceError as e:
    pass  # There was an error. Tell the user.
```

The first option is more explicit, and the `ResourceError` is raised as soon as the resource is added, if there was any issue. The second option seems less clear to me, but keeps the API consistent with how you add other attributes to the datapackage. As `dp.resources` can already raise a ResourceError, I have a slight preference for the second option.

**Comment by pwalsh** [comment]
Go with your preferred implementation.
