### ISSUE TITLE
Lazily load resources

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#20]
Related to #7. When I create a dataset like:

```python
import datapackage

metadata = {
    'name': 'foo',
    'resources': [
        {'name': 'the-resource', 'url': 'http://www.somewhere.com/data.csv'}
    ]
}
dp = datapackage.DataPackage(metadata)
# The resources' data shouldn't be loaded yet
data = dp.resources[0].data  # The data should be loaded here (if it wasn't yet)
```

This is useful for https://github.com/ckan/ckanext-datapackager/. When importing a datapackage into a dataset, I want to create a `DataPackage` to parse the datapackage, but I don't want to load its data.

**Comment by pwalsh** [comment]
@vitorbaptista ideally, when you have  data in a `url` or `path`, you would wrap it in tabulator exposed as `data`, and therefore you'd have an iterator. You'd never want to load the data as it could be disastrous for large resources.

BTW: expose `url` or `path` on `data` - great idea.

**Comment by pwalsh** [comment]
@vitorbaptista 

( cc @roll @akariv )

Now I understand that resources are loaded completely into memory when a datapackage is initialized. This is a really dangerous default: we have datapackages with gigabytes of data.

Two points:

* never load by default (as you opened this issue for)
* when we have tabular data, expose it as a stream using `tabulator` - never load a full table of data into memory

I know that because this lib can handle all sorts of resources, and not just tabular ones, this is not as straight forward as it seems. However, this is pretty high priority for the various integrations we are doing now.

Let's think here on a reasonable first implementation that addresses this.

**Comment by roll** [comment]
How to differ Data Package and Tabular Data Package (when we can use tabulator)?

**Comment by pwalsh** [comment]
@roll Tabular Data Package expects a tabular data source (CSV, Excel). In Data Package in general, it could be anything. example: an image.

**Comment by pwalsh** [comment]
@roll sorry, if you meant how can we tell, well, there is a `profiles` property on data packages that can tell us, but it is not required AFAIK. So I guess the best think we can do here is guess based on file extension.

**Comment by roll** [comment]
@pwalsh Yes, we have:

```
In addition to those basic rules, a valid Tabular Data Package package MUST conform to the following additional requirements:

It MUST contain at least one data file
All data files MUST be in CSV format, see below for additional rules on CSV file naming and structure
Every resource MUST have a schema following the JSON Table Schema specification
```

No so straight to implement logic to decide.

**Comment by pwalsh** [comment]
@roll yes. a really quick hack that would solve the vast majority of cases would be to wrap in tabulator if extension is CSV.

**Comment by roll** [comment]
@pwalsh +1

**Comment by roll** [comment]
I think it's very reasonable to use `tabulator` here for `TabularResource` resources - https://github.com/okfn/datapackage-py/blob/master/datapackage/resource.py#L160

Also `tabulator.loaders` can be used to load streams from different sources. But for non tabular data I don't see how API can look.

**Comment by roll** [comment]
May be it even could be a different package `tabular-datapackage-py` based on `datapackage-py` because we have to different specefications (and Data Package knows nothing about Tabular Data Package - no dependecy).

**Comment by roll** [comment]
```
Resource
    + data: string (load into memory when called)
TabularResource(Resource)
    + [inherited]
    + tabular_data/rows: iterable
    + reset?
```

**Comment by vitorbaptista** [comment]
@roll I'm thinking on exposing the `Table` class from tabulator on `datapackage.resources[0].data`, but from what I can see in https://github.com/okfn/tabulator-py/blob/master/tabulator/table.py, it's not an iterator on itself, right? So the user would have to know its API and call `readrow` or whatever.

IMHO, it would be better if it was an iterator, so the interface would be consistent with the rest of Python and the user (hopefully) wouldn't need to care that we use `tabulator` or not.

**Comment by roll** [comment]
@vitorbaptista 

This changes it's coming - https://github.com/okfn/tabulator-py/issues/14. 
Here will be an iterator like `table.rows(with_headers=True)`. Here is a question about Table as iterator because we have to options - with or without headers.

**Comment by vitorbaptista** [comment]
Usually, a method that takes a flag to change its behavior is actually two
methods hidden in one. If that's the case, there could be `table.rows` and
`table.rows_without_headers` (I'm supposing rows with the headers is the
most common case).

Actually, what's the use case of iterating without the headers?

**Comment by pwalsh** [comment]
-1 on this being two methods hidden as one. 

The Table takes processors that (potentially) modify the output. 

We can debate whether the output should be default with header or without, but this is def. not two distinct methods.

**Comment by vitorbaptista** [comment]
@pwalsh OK

@roll good point about `datapackage.resources[0].data` on binary data. We should strive to make the `.data` behaviour consistent across any type of resource (to avoid pushing this burden to the client), so it must be some iterator. As a binary file has no rows, the iterator would simply return all data in the first pass.

I'm not fond of having different methods for different resource types, because I think it will lead to code like:

```python
for resource in datapackage.resources:
    if isinstance(resource, TabularResource):
        resource.tabular_data  # do stuff
    elif isinstance(resource, ImageResource):
        resource.image_data  # do other stuff
    else:
        resource.data  # ...
```

I think that logic should be encapsulated inside the resources, so the user can do:

```python
for resource in datapackage.resources:
    for row in resource.data:
        # do stuff
```

The actual data will be of different types depending on the resource, so the user needs to know which type it is, but at least the interface is the same.

What do youu think?

**Comment by pwalsh** [comment]
++1 @vitorbaptista on consistent interface. I think you are on the right track here.

I don't think we need to be too concerned about non-tabular data right now, as the main application for DP is tabular data in CSV. So, we should ensure we are careful how we load into memory, but as long as we solve the tabular data issue nicely, I can live with some hacks for other resources right now :).

**Comment by roll** [comment]
@vitorbaptista 
> Actually, what's the use case of iterating without the headers?

The main use case is when a table doesn't have headers :-) But I think I've solved how to have table as iterator and with-headers/without-headers together. I'm going to implement it today.

About `if-elif-elif-efli` - yea you're right I was thinking *by mistake* that Tabular Data Package guarantee all resource to be tabular to use polymorphism here. But I'm still in doubts that `datapackage.resources[0].data` generating so different items (type incompatible) can be called a consistent interface. 

So I mean what will be better fo the end user:

```
for resource in datapackage.resources:
    for row in resource.data:
        # raise mysterious error because resource detected as not tabular and fails with some TypeError
```

or

```
for resource in datapackage.resources:
    print(resource.data.read()) # guaranteed bytearray for every type of resources
    if resource.row is not None:
        for row in resource.rows:
            # guaranteed iteration over tuples
    else:
        raise ValueError('Please fix your Data Package!')
```

For example `ImageResource` can provide other additional attributes to work with images etc. So user will be able to check if this attributes are available and use it.

I'm not even close to be sure how it has to be done - just thinking out loud.

**Comment by roll** [comment]
For example as client of the library writing BigQuery or SQL integration I'm anyway in need to be sure what type of resource I'm working with:

1. High-user gives me a Data Package
2. I don't know a structure of it
3. So I'm iterating over resources:
```
for resource in datapackage.resources:
    for something in resource.data:
        if isinstance(something, tuple):
             # put it as table
        elif isinstance(something, bytes):
             # save to S3 or ignore
        etc
```
The same `if-elif-elif` but know user is responsible to do all dirty work.

Again - just trying to give you more food for thought :)

**Comment by roll** [comment]
Updated Tabulator interface:

```python
from tabulator import topen, processors

with topen('path.csv') as table:
    table.add_processor(processors.Headers())
    for row in table:
        print(row)
        print(row.get('header'))
```

I'll mark it as `0.2.0` version when finish with Excel so it will be available to depend upon it.

**Comment by vitorbaptista** [comment]
Currently, you can lazily-load tabular resources through `TabularResource.iter()`. The `Resource.data` attribute gets the entire data. As @roll explained above, it's better to separate the two cases in two methods.

The implementation of `TabularResource.iter()` is quite messy. As `datapackage-py` needs to be able to work with any data type, it needs to be able to load data. Currently, there's no way to pass that data directly to `tabulator-py` for it to parse (it has to load the data as well). I've created an issue about it at https://github.com/okfn/tabulator-py/issues/24 and started working on a solution at https://github.com/vitorbaptista/tabulator-py/tree/topen-accepts-filelike-objects, but didn't go too far.

The `datapackage-py` interface shouldn't change when https://github.com/okfn/tabulator-py/issues/24 is done, though, so it's OK for now.

**Comment by vitorbaptista** [comment]
I was planning to refactor the code to pass a file-like object to Tabulator as soon as @roll added support for it. I didn't realize that one obvious caveat: I would have to pass the format to Tabulator when loading with a file-like object. Given that the current code is working, with the only issue being that it actually loads the file when it's a non-tabular resource, and delegates the loading to Tabulator when it's a tabular one, I think it's best to keep it as it is. This leaves the logic of testing the file format in Tabulator, where it belongs IMO.

That being the case, I'm closing this issue now.

@pwalsh if you disagree, please reopen it :+1:

**Comment by pwalsh** [comment]
@vitorbaptista not quite sure I get the issue, can you explain further. For sure, Tabulator does not and will not at this stage guess at file formats - it expects to be passed the format.

**Comment by vitorbaptista** [comment]
The issue was that the logic for actually reading the file (not parsing) is different depending on if it's a regular or a tabular resource. If it's a regular resource, we read the file ourselves (as tabulator doesn't and shouldn't support those). If it's a tabular resource, we just pass the path/url to tabulator and delegate the loading to it.

I was hoping to consolidate the file reading here, and leave just the parsing for tabulator. However, given that it's a minor issue, I don't think this refactoring is worth doing now. If we agree on that, this issue is done :+1:

**Comment by pwalsh** [comment]
ok done.
