### ISSUE TITLE
Shall we support ZIP files with datapackage.json inside an inner folder?

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#29]
The ZIPs generated by GitHub (e.g. https://github.com/datasets/gdp/archive/master.zip) have the repositories' contents inside a folder. If we were to support this pattern, we would have to look for the `datapackage.json` inside the ZIP and use its path as the datapackage's base path.

I remember reading the specs stating that the `datapackage.json` MUST be on the root of the ZIP file, so this issue might also require a spec change.

If we end up not supporting this, the user could simply create a datapackage passing the `datapackage.json` raw URL, as in https://raw.githubusercontent.com/datasets/gdp/master/datapackage.json, if she wants to load a datapackage hosted on GitHub.

**Comment by amercader** [comment]
I'm +1 on allowing a zipped folder with the `datapackage.json` inside as part of the spec. It's a general good practice to zip a folder and not the files at the root level.

**Comment by pwalsh** [comment]
@vitorbaptista @amercader zip has nothing to do with the Data Package specification. Any implementation we have here for handling zip files, while extremely handy, is not about compliance with the spec - just to clarify some of the points made above.

So, considering that, I don't think we should have any special case handling of zip files. What I do think is useful for consumers of the library would be the ability to pass in a path to the DP inside the zip file. I don't know if this is something that should be set on the constructor, or explicitly on the methods that handle zipping (into and out of), but something like:

```
def zip(zip_path='.'):
    # stuff

def unzip(zip_path='.'):
    # stuff
```

Where `zip_path` is a file path to the data package relative to the root of the zip.

**Comment by vitorbaptista** [comment]
I just found the part of the spec I was talking about:

> A valid data package MUST provide a data package “descriptor” file named datapackage.json.
> 
> This file should be placed in the top-level directory (relative to any other resources provided as part of the data package).

As @pwalsh said, it doesn't reference ZIPs or anything like that. It seems to mean that you can't have a resource with a path below the directory of the datapackage.json, but it's a bit unclear.

**Comment by vitorbaptista** [comment]
@pwalsh The reason I created this issue was to allow users to upload GitHub-generated ZIP files to CKAN using ckanext-datapackager. Considering this use case, allowing the library users to pass a zip_path doesn't help unless we alter ckanext-datapackager to look for a `datapackage.json` inside the ZIP file (if it's a ZIP file) and set the zip_path accordingly.

I would rather not do that, so all logic on handling datapackages is nicely encapsulated inside this package. If, in the future, we (say) start supporting .TAR files, ckanext-datapackager doesn't need to change at all.

Given that zipping the entire folder (instead of its contents) is generally considered a good practice (as per @amercader), I do think it's useful for us to support it. Just let's not go crazy and support only two basic patterns:

* datapackage.json inside the root folder;
* ZIP file a single folder with a datapackage.json in its root level.

In any other case, the datapackage loading must fail.

**Comment by pwalsh** [comment]
@vitorbaptista ok, go ahead.

**Comment by vitorbaptista** [comment]
Done :+1:

**Comment by vitorbaptista** [comment]
After https://github.com/okfn/datapackage-py/commit/10994869594026d338e51bdd7a5d5add5e01e063, `datapackage-py` will look for a `datapackage.json` anywhere inside the ZIP file and load it. If there are more than one `datapackage.json`, it'll raise an exception.

It was easier to do than to require the `datapackage.json` to only be on a single folder and such, so I went ahead and did this way.
