### ISSUE TITLE
Load data package schemas from the datapackage registry

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#4]
Ideally, this won't require a HTTP request for the basic data package types

https://github.com/okfn/datapackage-registry-py

**Comment by pwalsh** [comment]
*definitely* don't include the schemas here: that is why the `datapackage-registry` package exists.

Only as a further optimisation after that is integrated and working: see if there is a way we can fallback to some local cache of the schemas if http connection is not available. But, this is not something to optimise for until we have a working lib using `datapackage-registry`.

**Comment by vitorbaptista** [comment]
I wrote a proposal to solve this in https://github.com/okfn/datapackage-registry-py/issues/2.

**Comment by pwalsh** [comment]
@vitorbaptista ok, first let's see everything working as `datapackage_registry` as is, and then we'll tackle the issue there.
