### ISSUE TITLE
Figure out how to load resources with a relative path when DataPackage was created with a dict

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#5]
The issue is that the path is relative to the `datapackage.json` file, but if the user created the `DataPackage` object passing in a datapackage `dict`, we don't know where it came from, so we don't know its base path.

**Comment by pwalsh** [comment]
Maybe throw a warning telling the user to use `base` in cases where we can't know where the file is? I guess that does not really solve the problem for local paths.

**Comment by vitorbaptista** [comment]
The solution I've found was accepting a `default_base_path` on `DataPackage` that is used when the resource doesn't have a `base` attribute. The code currently raises an `ResourceException` if it can't load any resource as well. I thought it was better than silently ignoring this error and throwing at a later time (i.e. when the resources were actually accessed).

If you disagree, please open a new issue about it :+1:

**Comment by pwalsh** [comment]
@vitorbaptista sounds good.
