### ISSUE TITLE
The resources shouldn't be all allocated into memory by default

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#7]
They might be big, so it's better to use streaming when possible (e.g. when they're a local file)

**Comment by pwalsh** [comment]
@vitorbaptista we must always stream. I don't see any case where we would not stream.

**Comment by vitorbaptista** [comment]
@pwalsh I'm not sure how we would both stream data and validate its format (given that the `format` property isn't required). Maybe simply use the file or url's suffix, then we're just left with detecting the format of inline data (that should be small, so OK not to stream).

I suppose this is something that would be done on https://github.com/okfn/tabulator-py, so should makes things easier :+1:

**Comment by pwalsh** [comment]
@vitorbaptista yes, should all be handled in tabulator. But good point on format: it probably should be required otherwise building out tooling gets complicated fast.

**Comment by vitorbaptista** [comment]
This is discussed in #20
