### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#9]

**Comment by vitorbaptista** [comment]
- [ ] Configure readthedocs.com
- [ ] Add link in README
- [ ] Add usage examples in README

**Comment by vitorbaptista** [comment]
There's some issue with readthedocs that it's not extracting the code's doctests correctly

**Comment by pwalsh** [comment]
@vitorbaptista with small libraries like this, part of the benefit of them is not needing extensive documentation. Right now, a really good read with examples of use, and great docstrings in the code would be more than enough. The problem with a whole set of docs generated in Sphinx or [MKDoc](https://github.com/mkdocs/mkdocs/) for Read the Docs is that it becomes another thing in and of itself to maintain.

**Comment by vitorbaptista** [comment]
I agree, @pwalsh. My original plan was to just add docstrings and write some examples. After that was done, I realized that setting up readthedocs was trivial, so I ended up configuring it.

My current plan is just to add some usage examples, set up a hook in GitHub to update RTD on every push, and be done with it. It'll just be a way to read the docstrings without going through the code.

**Comment by vitorbaptista** [comment]
Closing this, as we won't use RTD.
